version: "3.0"
services:
   nginxservice:
      image: nginx:latest
      ports:
        - "80:80"
      deploy:
        replicas: 6
        restart_policy:
           condition: on-failure
        placement:
          constraints:
            - node.role == worker
 
